### ISSUE TITLE
Remove " (1)" from file names

### ISSUE THREAD

**Issue by ignasi35** [bcneng/bcneng.github.io#28] opened 2020-03-31 13:19 UTC
Logo files in the root of the repo (both SVG and PNG formats) are named `<name> (1).<extension>`. Rename those before they're being used from external resources.

**Comment by gonzaloserrano** [comment] 2020-04-05 19:16
In the soon-to-merge v2 branch the problem is gone so I'm closing this.

**Closed by gonzaloserrano** 2020-04-05 19:16 UTC
